server:
  port: '9091'

spring:
#  mvc:
#      pathmatch:
#          matching-strategy: ant_path_matcher
  application:
    name: prueba-tecnica
  datasource:
    driver-class-name: org.h2.Driver
    username: mau
    password: 123
    url: "jdbc:h2:mem:pruebatecnica;DB_CLOSE_ON_EXIT=FALSE"
  h2:
    console:
      enabled: true
      path: /h2-console
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.H2Dialect
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: create-drop
  springdoc:
    swagger-ui:
      path: /doc/swagger-ui.html